### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by joe9** [whitlockjc/swagger-lint#6]
Hello,

I cannot install swagger-lint. Can you please help?

`
npm install swagger-lint
npm ERR! Linux 3.18.25-gentoo-r1-20160524190147
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "swagger-lint"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/swagger-lint
npm ERR! 404
npm ERR! 404 'swagger-lint' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/j/dev/apps/swagger/npm-debug.log
`
Log file is at [https://gist.github.com/b8095e99c05ed50c9beafcbf0fe31f8b](https://gist.github.com/b8095e99c05ed50c9beafcbf0fe31f8b)

Thanks

**Comment by whitlockjc** [comment]
It's because we've not released yet.
